AWSTemplateFormatVersion: "2010-09-09"

Description: S3 Example - Seconday Region

Parameters:
  BucketName:
    Type: String
    Default: capital-saratoga-region-aws-user-group

Resources:
  MyBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${BucketName}-${AWS::Region}
      VersioningConfiguration:
        Status: Enabled
